"""
GraphQL components.
"""

# Import all fragments to make them available
from .data_contracts import (
    DATA_CONTRACT_FRAGMENT,
    DATA_CONTRACT_PROPERTIES_FRAGMENT,
    DATA_CONTRACT_SIMPLE_FRAGMENT,
    DATA_CONTRACT_STATUS_FRAGMENT,
    DATA_CONTRACT_WITH_DATASET_FRAGMENT,
)
from .metadata import CUSTOM_PROPERTIES_FRAGMENT
from .ownership import (
    OWNER_ENTITY_FRAGMENT,
    OWNERSHIP_FRAGMENT,
    OWNERSHIP_SIMPLE_FRAGMENT,
    OWNERSHIP_TYPE_FRAGMENT,
)
from .properties import STRUCTURED_PROPERTIES_FRAGMENT
