version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: datahub-recipes-manager
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data
      - app-recipes:/app/recipes
      - app-templates:/app/templates
      - app-metadata:/app/metadata-manager
      - ../:/app  # Mount source code for development
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:////app/data/recipes_manager.db
      - SECRET_KEY=dev_secret_key_change_in_production
      - DATAHUB_URL=${DATAHUB_URL:-http://localhost:8080}
      - DATAHUB_TOKEN=${DATAHUB_TOKEN:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
  app-recipes:
    driver: local
  app-templates:
    driver: local
  app-metadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/metadata-manager 