# DataHub Recipes Manager Configuration

# DataHub server connection details
datahub:
  gms_url: "http://localhost:8080"
  token: "${DATAHUB_TOKEN}"  # Using environment variable for secret

# Default recipe parameters
defaults:
  execution_id: "default_execution"
  pipeline_name: "default_pipeline"
  run_id: "default_run"
  
# Environment specific configurations
environments:
  dev:
    gms_url: "http://datahub-dev.example.com:8080"
    token_secret_name: "datahub-dev-token"
  
  staging:
    gms_url: "http://datahub-staging.example.com:8080"
    token_secret_name: "datahub-staging-token"
  
  prod:
    gms_url: "http://datahub-prod.example.com:8080"
    token_secret_name: "datahub-prod-token"

# Secret management configuration
secrets:
  provider: "env"  # Options: env, vault, aws-secrets-manager
  
  # Vault-specific configuration (used when provider is "vault")
  vault:
    url: "http://localhost:8200"
    auth_method: "token"
    token_path: "${HOME}/.vault-token"
    secret_path: "secret/datahub"

# Recipe templating configuration
templates:
  default_params_file: "params/default_params.yaml"
  output_dir: "generated_recipes" 