# Generated by Django 5.2.1 on 2025-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0001_initial"),
    ]

    operations = [
        # Step 1: Rename original_urn fields to temporary names to avoid conflicts
        migrations.RenameField(
            model_name='tag',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='glossarynode',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='glossaryterm',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='assertion',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='structuredproperty',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='dataproduct',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='original_urn',
            new_name='temp_urn',
        ),
        
        # Step 2: Rename deterministic_urn to urn
        migrations.RenameField(
            model_name='tag',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='glossarynode',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='glossaryterm',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='assertion',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='structuredproperty',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='dataproduct',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='deterministic_urn',
            new_name='urn',
        ),
        
        # Step 3: Drop the temporary urn fields
        migrations.RemoveField(
            model_name='tag',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='glossarynode',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='assertion',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='structuredproperty',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='temp_urn',
        ),
        migrations.RemoveField(
            model_name='test',
            name='temp_urn',
        ),
        
        # Step 4: Remove owners_count fields
        migrations.RemoveField(
            model_name='tag',
            name='owners_count',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='owners_count',
        ),
        migrations.RemoveField(
            model_name='assertion',
            name='owners_count',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='owners_count',
        ),
    ]
