# Generated by Django 5.2.2 on 2025-06-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataHubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urn", models.CharField(max_length=500, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "DataHub Group",
                "verbose_name_plural": "DataHub Groups",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DataHubUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urn", models.CharField(max_length=500, unique=True)),
                ("username", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "DataHub User",
                "verbose_name_plural": "DataHub Users",
                "ordering": ["username"],
            },
        ),
    ]
