# Generated by Django 5.2.1 on 2025-05-19 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0002_add_datahub_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("datahub_url", models.URLField(blank=True)),
                ("datahub_token", models.CharField(blank=True, max_length=255)),
                ("git_branch", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="staged_for_git",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="domain",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("SYNCED", "Synced"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                    ("PENDING_DELETION", "Pending Deletion"),
                ],
                default="LOCAL_ONLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="staged_for_git",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("SYNCED", "Synced"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                    ("PENDING_DELETION", "Pending Deletion"),
                ],
                default="LOCAL_ONLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="staged_for_git",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("SYNCED", "Synced"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                    ("PENDING_DELETION", "Pending Deletion"),
                ],
                default="LOCAL_ONLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="description",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="domain",
            name="deterministic_urn",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="original_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="deterministic_urn",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="original_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="deterministic_urn",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="original_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#0d6efd", max_length=20),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="deterministic_urn",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="original_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="domain",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="metadata_manager.environment",
            ),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glossary_nodes",
                to="metadata_manager.environment",
            ),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glossary_terms",
                to="metadata_manager.environment",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="metadata_manager.environment",
            ),
        ),
    ]
