# Generated by Django 5.2.1 on 2025-06-17 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0002_rename_urn_fields_and_remove_counts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assertion",
            name="relationships_count",
        ),
        migrations.RemoveField(
            model_name="dataproduct",
            name="entities_count",
        ),
        migrations.RemoveField(
            model_name="dataproduct",
            name="relationships_count",
        ),
    ]
