# Generated by Django 5.2.2 on 2025-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0002_datahubgroup_datahubuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="owners_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tag",
            name="ownership_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
