# Generated by Django 5.2.1 on 2025-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0003_remove_assertion_relationships_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="timeout",
            field=models.IntegerField(
                default=30, help_text="Connection timeout in seconds"
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="verify_ssl",
            field=models.BooleanField(default=True),
        ),
    ]
