# Generated by Django 5.2.2 on 2025-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0003_tag_owners_count_tag_ownership_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataHubOwnershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urn", models.CharField(max_length=500, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "DataHub Ownership Type",
                "verbose_name_plural": "DataHub Ownership Types",
                "ordering": ["name"],
            },
        ),
    ]
