# Generated by Django 4.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_manager', '0004_fix_environment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='domain_urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ] 