# Generated by Django 5.2.1 on 2025-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0004_datahubownershiptype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("cache_key", models.CharField(db_index=True, max_length=255)),
                ("current_step", models.CharField(max_length=200)),
                ("current_entity_type", models.CharField(blank=True, max_length=50)),
                ("current_platform", models.CharField(blank=True, max_length=100)),
                ("total_combinations", models.IntegerField(default=0)),
                ("completed_combinations", models.IntegerField(default=0)),
                ("total_results_found", models.IntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key", "cache_key"],
                        name="metadata_ma_session_809dc0_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="metadata_ma_updated_e7aef3_idx"
                    ),
                ],
                "unique_together": {("session_key", "cache_key")},
            },
        ),
        migrations.CreateModel(
            name="SearchResultCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("cache_key", models.CharField(db_index=True, max_length=255)),
                ("entity_urn", models.CharField(db_index=True, max_length=500)),
                ("entity_data", models.JSONField()),
                ("search_params", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key", "cache_key"],
                        name="metadata_ma_session_d62627_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="metadata_ma_created_732597_idx"
                    ),
                ],
                "unique_together": {("session_key", "cache_key", "entity_urn")},
            },
        ),
    ]
