# Generated by Django 5.2.1 on 2025-05-20 11:43
# This migration is now a placeholder since the columns were already added in 0004_add_missing_columns

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0004_add_missing_columns"),
    ]

    operations = [
        # No operations - columns already added in previous migration
    ]
