# Generated by Django 5.2.1 on 2025-05-23 11:30

from django.db import migrations, models


def update_sync_status(apps, schema_editor):
    """Update sync status values to new simplified choices"""
    Tag = apps.get_model('metadata_manager', 'Tag')
    GlossaryNode = apps.get_model('metadata_manager', 'GlossaryNode')
    GlossaryTerm = apps.get_model('metadata_manager', 'GlossaryTerm')
    Domain = apps.get_model('metadata_manager', 'Domain')
    
    # Update Tag sync status
    for tag in Tag.objects.all():
        if tag.sync_status == 'SYNCED':
            continue
        tag.sync_status = 'NOT_SYNCED'
        tag.save()
    
    # Update GlossaryNode sync status
    for node in GlossaryNode.objects.all():
        if node.sync_status == 'SYNCED':
            continue
        node.sync_status = 'NOT_SYNCED'
        node.save()
    
    # Update GlossaryTerm sync status
    for term in GlossaryTerm.objects.all():
        if term.sync_status == 'SYNCED':
            continue
        term.sync_status = 'NOT_SYNCED'
        term.save()
    
    # Update Domain sync status
    for domain in Domain.objects.all():
        if domain.sync_status == 'SYNCED':
            continue
        domain.sync_status = 'NOT_SYNCED'
        domain.save()


class Migration(migrations.Migration):
    dependencies = [
        ('metadata_manager', '0004_add_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='sync_status',
            field=models.CharField(
                choices=[
                    ('SYNCED', 'Synced'),
                    ('NOT_SYNCED', 'Not Synced'),
                ],
                default='NOT_SYNCED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='glossarynode',
            name='sync_status',
            field=models.CharField(
                choices=[
                    ('SYNCED', 'Synced'),
                    ('NOT_SYNCED', 'Not Synced'),
                ],
                default='NOT_SYNCED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='sync_status',
            field=models.CharField(
                choices=[
                    ('SYNCED', 'Synced'),
                    ('NOT_SYNCED', 'Not Synced'),
                ],
                default='NOT_SYNCED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='domain',
            name='sync_status',
            field=models.CharField(
                choices=[
                    ('SYNCED', 'Synced'),
                    ('NOT_SYNCED', 'Not Synced'),
                ],
                default='NOT_SYNCED',
                max_length=20,
            ),
        ),
        migrations.RunPython(update_sync_status),
    ] 