# Generated by Django 5.2.1 on 2025-06-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0004_add_environment_datahub_config"),
        ("web_ui", "0003_add_connection_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="timeout",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="verify_ssl",
        ),
        migrations.AddField(
            model_name="assertion",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="dataproduct",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="structuredproperty",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_ui.connection",
            ),
        ),
    ]
