# Generated by Django 5.2.1 on 2025-05-20 13:55
# This migration is a placeholder since the fields were already added in 0004_add_missing_columns

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0006_domain_datahub_id_glossarynode_datahub_id_and_more"),
    ]

    operations = [
        # No operations - fields were already added in previous migrations
    ]
