# Generated by Django 5.2.1 on 2025-06-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0006_remove_environment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossarynode",
            name="ownership_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="ownership_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
