# Generated by Django 5.2.1 on 2025-05-20 14:01
# This migration is used to mark the db as being in sync with the models

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0007_domain_datahub_id_glossarynode_datahub_id_and_more"),
    ]

    # Telling Django that the models in models.py match the current database state
    operations = []
