# Generated by Django 5.2.1 on 2025-06-18 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0007_add_ownership_data_to_glossary"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossarynode",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glossary_nodes",
                to="metadata_manager.domain",
            ),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="relationships_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="relationships_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
