# Generated by Django 5.2.1 on 2025-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0008_add_additional_glossary_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assertion",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="structuredproperty",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
