# Generated by Django 5.2.1 on 2025-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0008_fake_all_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="datahub_id",
            field=models.CharField(
                blank=True, help_text="ID in DataHub", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="glossarynode",
            name="datahub_id",
            field=models.CharField(
                blank=True, help_text="ID in DataHub", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="datahub_id",
            field=models.CharField(
                blank=True, help_text="ID in DataHub", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="datahub_id",
            field=models.CharField(
                blank=True, help_text="ID in DataHub", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="staged_for_git",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("SYNCED", "Synced"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                    ("PENDING_DELETION", "Pending Deletion"),
                ],
                default="LOCAL_ONLY",
                max_length=20,
            ),
        ),
    ]
