# Generated by Django 5.2.1 on 2025-06-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0009_alter_assertion_urn_alter_dataproduct_urn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryterm",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glossary_terms",
                to="metadata_manager.domain",
            ),
        ),
    ]
