# Generated by Django 5.2.1 on 2025-06-02 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0005_glossaryterm_domain_urn"),
        ("metadata_manager", "0005_simplify_sync_status"),
        ("metadata_manager", "0009_domain_datahub_id_glossarynode_datahub_id_and_more"),
    ]

    operations = []
