# Generated by Django 5.2.1 on 2025-06-18 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0010_add_domain_to_glossary_term"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glossarynode",
            name="domain",
        ),
    ]
