# Generated by Django 5.2.1 on 2025-06-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0011_remove_domain_from_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossarynode",
            name="deprecated",
            field=models.BooleanField(
                default=False, help_text="Whether this node is deprecated"
            ),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="deprecated",
            field=models.BooleanField(
                default=False, help_text="Whether this term is deprecated"
            ),
        ),
    ]
