# Generated by Django 5.2.1 on 2025-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0011_add_structured_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="color_hex",
            field=models.CharField(
                blank=True,
                help_text="Color in hex format (e.g. #FF5733)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="icon_library",
            field=models.CharField(
                blank=True, default="font-awesome", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="icon_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="icon_style",
            field=models.CharField(
                blank=True, default="solid", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="owners_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="domain",
            name="parent_domain_urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="relationships_count",
            field=models.IntegerField(default=0),
        ),
    ]
