# Generated by Django 5.2.1 on 2025-06-09 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0012_add_domain_display_properties"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assertion",
            options={
                "ordering": ["name"],
                "verbose_name": "Assertion",
                "verbose_name_plural": "Assertions",
            },
        ),
        migrations.AddField(
            model_name="assertion",
            name="assertion_type",
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),
        migrations.AddField(
            model_name="assertion",
            name="datahub_id",
            field=models.CharField(
                blank=True, help_text="ID in DataHub", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="deterministic_urn",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assertion",
            name="entity_urn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metadata_manager.environment",
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="info_data",
            field=models.JSONField(
                blank=True, help_text="Complete info structure from DataHub", null=True
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="monitor_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="original_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assertion",
            name="owners_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assertion",
            name="ownership_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="platform_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="relationships_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assertion",
            name="relationships_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assertion",
            name="run_events_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assertion",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="tags_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assertion",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assertion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="assertion",
            name="description",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assertion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="assertion",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="assertion",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
