# Generated by Django 5.2.1 on 2025-06-20 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0012_add_deprecated_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glossarynode",
            name="relationships_data",
        ),
    ]
