# Generated by Django 5.2.2 on 2025-06-10 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metadata_manager",
            "0013_alter_assertion_options_assertion_assertion_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deterministic_urn", models.CharField(max_length=255, unique=True)),
                ("original_urn", models.CharField(blank=True, max_length=255)),
                (
                    "datahub_id",
                    models.CharField(
                        blank=True, help_text="ID in DataHub", max_length=255, null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("LOCAL_ONLY", "Local Only"),
                            ("REMOTE_ONLY", "Remote Only"),
                            ("MODIFIED", "Modified"),
                            ("PENDING_PUSH", "Pending Push"),
                        ],
                        default="NOT_SYNCED",
                        max_length=20,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "entity_urns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of entity URNs that belong to this data product",
                    ),
                ),
                ("domain_urn", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "platform_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("removed", models.BooleanField(default=False)),
                (
                    "properties_data",
                    models.JSONField(
                        blank=True,
                        help_text="Complete properties structure from DataHub",
                        null=True,
                    ),
                ),
                ("ownership_data", models.JSONField(blank=True, null=True)),
                ("owners_count", models.IntegerField(default=0)),
                ("relationships_data", models.JSONField(blank=True, null=True)),
                ("relationships_count", models.IntegerField(default=0)),
                ("entities_data", models.JSONField(blank=True, null=True)),
                ("entities_count", models.IntegerField(default=0)),
                ("tags_data", models.JSONField(blank=True, null=True)),
                ("glossary_terms_data", models.JSONField(blank=True, null=True)),
                ("structured_properties_data", models.JSONField(blank=True, null=True)),
                ("institutional_memory_data", models.JSONField(blank=True, null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metadata_manager.environment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Product",
                "verbose_name_plural": "Data Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataProductResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(max_length=20)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "data_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_results",
                        to="metadata_manager.dataproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Product Result",
                "verbose_name_plural": "Data Product Results",
                "ordering": ["-deployed_at"],
            },
        ),
    ]
