# Generated by Django 5.2.1 on 2025-06-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0014_add_ownership_data_to_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuredproperty",
            name="allowed_entity_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Entity types allowed as values for URN properties",
                null=True,
            ),
        ),
    ]
