# Generated by Django 5.2.2 on 2025-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0014_dataproduct_dataproductresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assertion",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="glossarynode",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="glossaryterm",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="structuredproperty",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_SYNCED", "Not Synced"),
                    ("SYNCED", "Synced"),
                    ("LOCAL_ONLY", "Local Only"),
                    ("REMOTE_ONLY", "Remote Only"),
                    ("MODIFIED", "Modified"),
                    ("PENDING_PUSH", "Pending Push"),
                ],
                default="NOT_SYNCED",
                max_length=20,
            ),
        ),
    ]
