# Generated by Django 5.2.1 on 2025-06-22 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0015_add_allowed_entity_types_to_structured_property"),
        ("web_ui", "0011_add_datahub_gc_recipe_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("urn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "datahub_id",
                    models.CharField(
                        blank=True, help_text="ID in DataHub", max_length=255, null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("NOT_SYNCED", "Not Synced"),
                            ("SYNCED", "Synced"),
                            ("LOCAL_ONLY", "Local Only"),
                            ("REMOTE_ONLY", "Remote Only"),
                            ("MODIFIED", "Modified"),
                            ("PENDING_PUSH", "Pending Push"),
                        ],
                        default="NOT_SYNCED",
                        max_length=20,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_urn", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "state",
                    models.CharField(
                        default="ACTIVE",
                        help_text="Contract state (ACTIVE, PENDING, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        help_text="Result type (PASSING, FAILING, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
                ("removed", models.BooleanField(default=False)),
                (
                    "properties_data",
                    models.JSONField(
                        blank=True,
                        help_text="Complete properties structure from DataHub",
                        null=True,
                    ),
                ),
                (
                    "status_data",
                    models.JSONField(
                        blank=True, help_text="Contract status information", null=True
                    ),
                ),
                ("structured_properties_data", models.JSONField(blank=True, null=True)),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, help_text="Contract result information", null=True
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_ui.connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Contract",
                "verbose_name_plural": "Data Contracts",
                "ordering": ["name"],
            },
        ),
    ]
