# Generated by Django 5.0.6 on 2024-06-23 22:05

from django.db import migrations


def fix_structured_property_urns(apps, schema_editor):
    """
    Fix structured property URNs from lowercase 'structuredproperty' to camelCase 'structuredProperty'
    """
    StructuredProperty = apps.get_model('metadata_manager', 'StructuredProperty')
    
    # Find all properties with the wrong URN format
    properties_to_fix = StructuredProperty.objects.filter(urn__contains='urn:li:structuredproperty:')
    
    for prop in properties_to_fix:
        # Replace lowercase with camelCase
        old_urn = prop.urn
        new_urn = old_urn.replace('urn:li:structuredproperty:', 'urn:li:structuredProperty:')
        prop.urn = new_urn
        prop.save(update_fields=['urn'])
        print(f"Fixed URN: {old_urn} -> {new_urn}")


def reverse_fix_structured_property_urns(apps, schema_editor):
    """
    Reverse the URN fix (camelCase back to lowercase)
    """
    StructuredProperty = apps.get_model('metadata_manager', 'StructuredProperty')
    
    # Find all properties with the camelCase URN format
    properties_to_revert = StructuredProperty.objects.filter(urn__contains='urn:li:structuredProperty:')
    
    for prop in properties_to_revert:
        # Replace camelCase with lowercase
        old_urn = prop.urn
        new_urn = old_urn.replace('urn:li:structuredProperty:', 'urn:li:structuredproperty:')
        prop.urn = new_urn
        prop.save(update_fields=['urn'])
        print(f"Reverted URN: {old_urn} -> {new_urn}")


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_manager', '0018_add_remote_deleted_sync_status'),
    ]

    operations = [
        migrations.RunPython(
            fix_structured_property_urns,
            reverse_fix_structured_property_urns,
        ),
    ]
