# Generated by Django 5.2.1 on 2025-06-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0019_fix_structured_property_urn_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="metadata_manager.environment",
            ),
        ),
    ]
