# Generated by Django 5.2.1 on 2025-06-23 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0020_domain_environment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="environment",
        ),
    ]
