# Generated by Django 5.2.1 on 2025-06-23 20:33

from django.db import migrations, models


def update_icon_library_to_material(apps, schema_editor):
    """Update existing domains from font-awesome to MATERIAL"""
    Domain = apps.get_model('metadata_manager', 'Domain')
    
    # Update all domains that have font-awesome icon_library to MATERIAL
    updated_count = Domain.objects.filter(icon_library='font-awesome').update(icon_library='MATERIAL')
    print(f"Updated {updated_count} domains from font-awesome to MATERIAL")
    
    # Update any domains with null icon_library to MATERIAL
    null_updated_count = Domain.objects.filter(icon_library__isnull=True).update(icon_library='MATERIAL')
    print(f"Updated {null_updated_count} domains with null icon_library to MATERIAL")


def reverse_icon_library_to_font_awesome(apps, schema_editor):
    """Reverse the migration by updating MATERIAL back to font-awesome"""
    Domain = apps.get_model('metadata_manager', 'Domain')
    
    # Update all domains that have MATERIAL icon_library back to font-awesome
    updated_count = Domain.objects.filter(icon_library='MATERIAL').update(icon_library='font-awesome')
    print(f"Reverted {updated_count} domains from MATERIAL to font-awesome")


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0021_remove_domain_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="icon_library",
            field=models.CharField(
                blank=True, default="MATERIAL", max_length=50, null=True
            ),
        ),
        migrations.RunPython(
            update_icon_library_to_material,
            reverse_icon_library_to_font_awesome,
        ),
    ]
