# Generated by Django 5.2.1 on 2025-06-23 20:58

from django.db import migrations, models


def revert_material_to_font_awesome(apps, schema_editor):
    """Revert any MATERIAL icon libraries back to font-awesome for UI consistency"""
    Domain = apps.get_model('metadata_manager', 'Domain')
    
    # Update all domains that have MATERIAL icon_library to font-awesome
    updated_count = Domain.objects.filter(icon_library='MATERIAL').update(icon_library='font-awesome')
    print(f"Reverted {updated_count} domains from MATERIAL to font-awesome")


def reverse_revert_material_to_font_awesome(apps, schema_editor):
    """Reverse migration - convert font-awesome back to MATERIAL if needed"""
    # This is a no-op since we want to keep font-awesome as the standard
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_manager', '0022_update_icon_library_to_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='icon_library',
            field=models.CharField(blank=True, default='font-awesome', max_length=50, null=True),
        ),
        migrations.RunPython(
            revert_material_to_font_awesome,
            reverse_revert_material_to_font_awesome,
        ),
    ]
