# Generated by Django 5.2.1 on 2025-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0023_revert_icon_library_to_font_awesome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="icon_library",
            field=models.CharField(
                blank=True, default="MATERIAL", max_length=50, null=True
            ),
        ),
    ]
