# Generated by Django 5.2.1 on 2025-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0024_add_mutation_entity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assertion",
            name="platform_instance",
            field=models.CharField(
                blank=True,
                help_text="Platform instance of the dataset",
                max_length=100,
                null=True,
            ),
        ),
    ]
