# Generated by Django 5.2.1 on 2025-06-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata_manager", "0025_add_platform_instance_to_assertion"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="entity_urn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="platform_instance",
            field=models.CharField(
                blank=True,
                help_text="Platform instance of the dataset",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="platform_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
