# Generated by Django 5.2.1 on 2025-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="datahub_token",
            field=models.CharField(
                blank=True, help_text="DataHub access token", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="datahub_url",
            field=models.URLField(blank=True, help_text="DataHub server URL"),
        ),
        migrations.AddField(
            model_name="environment",
            name="timeout",
            field=models.IntegerField(
                default=30, help_text="Connection timeout in seconds"
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="verify_ssl",
            field=models.BooleanField(
                default=True,
                help_text="Verify SSL certificates for DataHub connections",
            ),
        ),
    ]
