# Generated by Django 5.2.1 on 2025-06-13 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "platform_instance",
                    models.CharField(
                        help_text="Platform instance identifier", max_length=255
                    ),
                ),
                (
                    "env",
                    models.CharField(
                        help_text="Environment identifier", max_length=255
                    ),
                ),
                (
                    "custom_properties",
                    models.JSONField(
                        default=dict, help_text="Custom properties as JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Mutations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="environment",
            name="mutations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environments",
                to="web_ui.mutation",
            ),
        ),
    ]
