# Generated by Django 5.2 on 2025-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0002_logentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("recipe_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
