# Generated by Django 5.2.1 on 2025-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0002_add_datahub_fields_to_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this connection",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this connection",
                        null=True,
                    ),
                ),
                (
                    "datahub_url",
                    models.URLField(
                        help_text="DataHub GMS URL (e.g., https://your-datahub.com)"
                    ),
                ),
                (
                    "datahub_token",
                    models.CharField(
                        blank=True,
                        help_text="DataHub access token",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=True, help_text="Verify SSL certificates"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=30, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this connection is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default connection",
                    ),
                ),
                (
                    "last_tested",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time connection was tested",
                        null=True,
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if connection failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DataHub Connection",
                "verbose_name_plural": "DataHub Connections",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="environment",
            name="datahub_token",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="datahub_url",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="timeout",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="verify_ssl",
        ),
    ]
