# Generated by Django 5.2.1 on 2025-06-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0002_mutation_environment_mutations"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataHubClientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="DataHub client ID", max_length=255, unique=True
                    ),
                ),
                (
                    "server_id",
                    models.CharField(
                        blank=True,
                        help_text="DataHub server ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "frontend_base_url",
                    models.URLField(
                        blank=True, help_text="DataHub frontend base URL", null=True
                    ),
                ),
                (
                    "server_config",
                    models.JSONField(
                        default=dict, help_text="Raw server configuration as JSON"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_connection_test", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if connection failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        help_text="Environment this client info belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datahub_client_info",
                        to="web_ui.environment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DataHub Client Info",
                "ordering": ["-last_updated"],
                "unique_together": {("client_id", "environment")},
            },
        ),
    ]
