# Generated by Django 5.2 on 2025-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0003_recipetemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_id", models.CharField(max_length=255)),
                ("variable_name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("recipe_id", "variable_name")},
            },
        ),
    ]
