# Generated by Django 5.2.1 on 2025-06-17 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0004_migrate_appsettings_to_connection"),
        ("web_ui", "0004_remove_environmentinstance"),
    ]

    operations = []
