# Generated by Django 5.2 on 2025-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0005_githubpr_githubsettings_pullrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipesecret",
            name="is_secret",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipesecret",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
