# Generated by Django 5.2 on 2025-04-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0007_envvarstemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("policy_type", models.CharField(max_length=50)),
                ("state", models.CharField(default="ACTIVE", max_length=20)),
                ("content", models.TextField()),
                ("resources", models.TextField(blank=True, null=True)),
                ("privileges", models.TextField(blank=True, null=True)),
                ("actors", models.TextField(blank=True, null=True)),
                ("deployed", models.BooleanField(default=False)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "datahub_urn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="recipetemplate",
            name="datahub_urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipetemplate",
            name="deployed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipetemplate",
            name="deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EnvVarsInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("recipe_id", models.CharField(blank=True, max_length=255, null=True)),
                ("recipe_type", models.CharField(max_length=50)),
                ("variables", models.TextField()),
                ("deployed", models.BooleanField(default=False)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("datahub_secrets_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_ui.envvarstemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "datahub_urn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("deployed", models.BooleanField(default=False)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "env_vars_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_ui.envvarsinstance",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_ui.recipetemplate",
                    ),
                ),
            ],
        ),
    ]
