# Generated by Django 5.2 on 2025-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0008_policytemplate_recipetemplate_datahub_urn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envvarsinstance",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("kafka", "Kafka"),
                    ("file", "File"),
                    ("s3", "S3"),
                    ("snowflake", "Snowflake"),
                    ("bigquery", "BigQuery"),
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("oracle", "Oracle"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="envvarstemplate",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("kafka", "Kafka"),
                    ("file", "File"),
                    ("s3", "S3"),
                    ("snowflake", "Snowflake"),
                    ("bigquery", "BigQuery"),
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("oracle", "Oracle"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="envvarstemplate",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="envvarstemplate",
            name="variables",
            field=models.TextField(blank=True, null=True),
        ),
    ]
