# Generated by Django 5.2 on 2025-04-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0009_alter_envvarsinstance_recipe_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubsettings",
            name="current_branch",
            field=models.CharField(
                default="main",
                help_text="Current branch for GitHub operations",
                max_length=255,
            ),
        ),
    ]
