# Generated by Django 5.2 on 2025-05-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0010_githubsettings_current_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("METADATA", "Metadata"), ("PLATFORM", "Platform")],
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        max_length=50,
                    ),
                ),
                ("resources", models.TextField()),
                ("privileges", models.TextField()),
                ("actors", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.CreateModel(
            name="EnvironmentInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "recipe_type",
                    models.CharField(
                        choices=[
                            ("postgres", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mssql", "Microsoft SQL Server"),
                            ("snowflake", "Snowflake"),
                            ("bigquery", "BigQuery"),
                            ("redshift", "Redshift"),
                            ("databricks", "Databricks"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tenant", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="web_ui.envvarstemplate",
                    ),
                ),
            ],
        ),
    ]
