# Generated by Django 5.2.1 on 2025-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0011_add_datahub_gc_recipe_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutation",
            name="platform_instance_mapping",
            field=models.JSONField(
                default=dict,
                help_text="Platform instance mapping (from -> to) for syncing between environments",
            ),
        ),
    ]
