# Generated by Django 5.2 on 2025-05-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0011_policy_environmentinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeinstance",
            name="env_vars_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="web_ui.envvarsinstance",
            ),
        ),
    ]
