# Generated by Django 5.2.1 on 2025-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0012_add_platform_instance_mapping_to_mutation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutation",
            name="apply_to_domains",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to domains"
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="apply_to_glossary_terms",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="apply_to_structured_properties",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to structured properties"
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="apply_to_tags",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to tags"
            ),
        ),
    ]
