# Generated by Django 5.2.1 on 2025-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0013_add_mutation_entity_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation",
            name="env",
            field=models.CharField(
                blank=True,
                help_text="Environment identifier (deprecated - use platform_instance_mapping)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="platform_instance",
            field=models.CharField(
                blank=True,
                help_text="Platform instance identifier (deprecated - use platform_instance_mapping)",
                max_length=255,
                null=True,
            ),
        ),
    ]
