# Generated by Django 5.2.1 on 2025-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0014_make_mutation_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutation",
            name="apply_to_data_products",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to data products"
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="apply_to_glossary_nodes",
            field=models.BooleanField(
                default=False, help_text="Apply mutations to glossary nodes"
            ),
        ),
    ]
