# Generated by Django 5.2.1 on 2025-07-16 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0015_add_glossary_nodes_data_products_to_mutations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutation',
            name='platform_instance',
        ),
    ]
