# Generated by Django 5.2 on 2025-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0021_git_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitSecrets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_configured", models.BooleanField(default=True)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GitHub Secret",
                "verbose_name_plural": "GitHub Secrets",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="logentry",
            name="source",
            field=models.CharField(default="application", max_length=255),
        ),
    ]
