# Generated by Django 5.2 on 2025-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0023_alter_logentry_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeinstance",
            name="cron_schedule",
            field=models.CharField(default="0 0 * * *", max_length=100),
        ),
        migrations.AddField(
            model_name="recipeinstance",
            name="debug_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipeinstance",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
