# Generated by Django 5.2 on 2025-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0024_recipeinstance_cron_schedule_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gitsecrets",
            options={
                "ordering": ["environment", "name"],
                "verbose_name": "GitHub Secret",
                "verbose_name_plural": "GitHub Secrets",
            },
        ),
        migrations.AddField(
            model_name="gitsecrets",
            name="environment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="envvarsinstance",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("bigquery", "Google BigQuery"),
                    ("file", "File"),
                    ("s3", "Amazon S3"),
                    ("snowflake", "Snowflake"),
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("oracle", "Oracle"),
                    ("dbt", "dbt"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="envvarstemplate",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("bigquery", "Google BigQuery"),
                    ("file", "File"),
                    ("s3", "Amazon S3"),
                    ("snowflake", "Snowflake"),
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("oracle", "Oracle"),
                    ("dbt", "dbt"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gitsecrets",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="gitsecrets",
            unique_together={("name", "environment")},
        ),
    ]
