# Generated by Django 5.2 on 2025-05-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0025_alter_gitsecrets_options_gitsecrets_environment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="web_ui.environment",
            ),
        ),
    ]
