# Generated by Django 5.2 on 2025-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0026_policy_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipetemplate",
            name="executor_id",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
