# Generated by Django 5.2.2 on 2025-06-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("recipe_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("executor_id", models.CharField(default="default", max_length=50)),
                ("cron_schedule", models.CharField(default="0 0 * * *", max_length=50)),
                ("timezone", models.CharField(default="Etc/UTC", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
