name: Patch DataHub Recipe

on:
  workflow_dispatch:
    inputs:
      recipe_id:
        description: 'ID of the DataHub ingestion source to patch'
        required: true
      recipe_file:
        description: 'Path to the modified recipe file (relative to repository root)'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  patch-recipe:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Patch ingestion recipe
        run: python scripts/push_recipe.py --instance ${{ github.event.inputs.recipe_file }} --patch
        env:
          DATAHUB_GMS_URL: ${{ secrets.DATAHUB_GMS_URL }}
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }} 