name: Run DataHub Recipe Now

on:
  workflow_dispatch:
    inputs:
      recipe_id:
        description: 'Recipe ID to run immediately'
        required: true
        type: string
      environment:
        description: 'Environment to run in'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  run-recipe:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run ingestion recipe
        run: python scripts/run_recipe.py --recipe-id ${{ github.event.inputs.recipe_id }}
        env:
          DATAHUB_GMS_URL: ${{ secrets.DATAHUB_GMS_URL }}
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }} 