name: Test DataHub Integration

on:
  push:
    branches: [ main ]
    paths:
      - 'utils/**/*.py'
      - 'scripts/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'utils/**/*.py'
      - 'scripts/**/*.py'
  workflow_dispatch:

jobs:
  test-datahub-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test environment
        run: |
          echo "Setting up test environment..."
          ./test/setup_test_env.sh
      
      - name: Run unit tests
        run: |
          echo "Running Python unit tests..."
          python -m pytest -v

      - name: Test GraphQL client
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'test-graph') }}
        env:
          DATAHUB_GMS_URL: ${{ secrets.DATAHUB_GMS_URL }}
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }}
        run: |
          echo "Testing DataHub Graph integration..."
          ./scripts/test_graph.py
      
      - name: Run integration tests
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'test-integration') }}
        env:
          DATAHUB_GMS_URL: ${{ secrets.DATAHUB_GMS_URL }}
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }}
        run: |
          echo "Running integration tests..."
          ./test/run_all_tests.sh 